version: '3'

services:
  nginx:
    container_name: hubgamers-front
    image: alexisbriet/vuejs-nginx:latest
    ports:
      - "3000:80"
    networks:
      - hubgamers-network

networks:
  hubgamers-network:
    external: true
