name: Deploy Vue.js App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the Vue.js app
        run: npm run build-only

      - name: Create Nginx.conf
        run: touch nginx.conf

      - name: Build Docker image
        run: docker build -t vuejs-nginx .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag vuejs-nginx ${{ secrets.DOCKER_USERNAME }}/vuejs-nginx:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/vuejs-nginx:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/vuejs-nginx:latest
            docker stop vuejs-nginx || true
            docker rm vuejs-nginx || true
            docker run -d -p 3000:80 --name vuejs-nginx ${{ secrets.DOCKER_USERNAME }}/vuejs-nginx:latest
